// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_tUfDabnx2KGYcU8II1kmSLkWu7j_lTo',
    appId: '1:518131830711:web:93ebd972dead10c9202232',
    messagingSenderId: '518131830711',
    projectId: 'user-avatar-872135',
    authDomain: 'user-avatar-872135.firebaseapp.com',
    storageBucket: 'user-avatar-872135.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ9qj5qqsT97ZZtNK3MXai1zH36oqfX-8',
    appId: '1:518131830711:android:44cd22ab6d62712b202232',
    messagingSenderId: '518131830711',
    projectId: 'user-avatar-872135',
    storageBucket: 'user-avatar-872135.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdO9kKm1Uqzutc8SstpSEq6Ky-O6LM6pQ',
    appId: '1:518131830711:ios:2897e4dfc0c45fab202232',
    messagingSenderId: '518131830711',
    projectId: 'user-avatar-872135',
    storageBucket: 'user-avatar-872135.appspot.com',
    iosClientId: '518131830711-b03ap5bgn5bj3q4kcd75shmhi050l8qc.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdO9kKm1Uqzutc8SstpSEq6Ky-O6LM6pQ',
    appId: '1:518131830711:ios:2897e4dfc0c45fab202232',
    messagingSenderId: '518131830711',
    projectId: 'user-avatar-872135',
    storageBucket: 'user-avatar-872135.appspot.com',
    iosClientId: '518131830711-b03ap5bgn5bj3q4kcd75shmhi050l8qc.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
