import 'dart:convert';

import 'package:app/presentation/scholarships/model/scholarship.dart';
import 'package:http/http.dart' as http;
import 'dart:async';

class ScholarshipR {
  final url = Uri.parse("http://192.168.137.225:3500/api/v1/scholarship");

  Future<List<Data>> getAllPosts() async {
    final response = await http.get(url);
    return allPostsFromJson(response.body);
  }

// Future<Data> getPost() async {
//   final response = await http.get('$url/1');
//   return postFromJson(response.body);
// }

  Data postFromJson(String str) {
    final jsonData = json.decode(str);
    return Data.fromJson(jsonData);
  }

  String postToJson(Data data) {
    final dyn = data.toJson();
    return json.encode(dyn);
  }

  List<Data> allPostsFromJson(String str) {
    final jsonData = json.decode(str);
    Autogenerated data = Autogenerated.fromJson(jsonData);
    final list = data.data;
  return list!;
  }

  String allPostsToJson(List<Data> data) {
    final dyn = new List<dynamic>.from(data.map((x) => x.toJson()));
    return json.encode(dyn);
  }
}
